name: wsalamp-development-deployment
on:
  push:
    branches:
      development
jobs:
  build:
    runs-on: andromeda-self-runner
    steps:
      - name: Development Checkout
        uses: actions/checkout@v2
        with:
          path: wsalampdev

        # Development deployment.
        # Run shell commands from the hosted runner as beanstalk.
        # secrets.WSALAMP_DEV_PATH is a reference to the vhost on the dev servers.
      - run: |
          rsync  -rlptD --delete  $GITHUB_WORKSPACE/wsalampdev/* wsalampdev01:${{ secrets.WSALAMP_DEV_PATH }}/
          rsync  -rlptD --delete  $GITHUB_WORKSPACE/wsalampdev/* wsalampdev02:${{ secrets.WSALAMP_DEV_PATH }}/