name: wsalamp-production-deployment
on:
  pull_request:
    branches:
      main
    types: [ closed ]
jobs:
  build:
    # Only triggers on successfully approved pull requests.
    if: github.event.pull_request.merged == true
    runs-on: andromeda-self-runner

    steps:
      - name: Production Checkout
        uses: actions/checkout@v2
        with:
          path: wsalampprod

        # Production deployment.
      - run: |
          rsync -rlptD --delete --chown=beanstalk:webserv $GITHUB_WORKSPACE/wsalampprod/* wsalamp01:${{ secrets.WSALAMP_PROD_PATH }}/
          rsync -rlptD --delete --chown=beanstalk:webserv $GITHUB_WORKSPACE/wsalampprod/* wsalamp02:${{ secrets.WSALAMP_PROD_PATH }}/
          rsync -rlptD --delete --chown=beanstalk:webserv $GITHUB_WORKSPACE/wsalampprod/* wsalamp03:${{ secrets.WSALAMP_PROD_PATH }}/